Odontech/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('', include('staticpages.urls')),
    path("admin/", admin.site.urls),
    path('', include('contas.urls')),
    path('funcionarios/', include('funcionarios.urls')),
    path('consultas/', include('consultas.urls')),
    path('exames/', include('exames.urls')),
    path('procedimentos/', include('procedimentos.urls')),
    path('pacientes/', include('pacientes.urls')),
    path('', include('django.contrib.auth.urls')),
]

consultas/urls.py
from django.urls import path
from .views import *

app_name = 'consultas'

urlpatterns = [
    path('', ListaConsultasView.as_view(), name='lista_consultas'),
    path('agendar/<int:pk>/dentista/', CriarConsultaDentistaView.as_view(), name='Dentistacriar_consulta'),
    path('agendar/<int:pk>/', CriarConsultaView.as_view(), name='criar_consulta'),
    path('agendar/selecionaDent/', SelecionaDentistaView, name='selecionaDentista'),
    path('detalhes/<int:pk>/', ConsultaDetailView.as_view(), name='detalhes_consulta'), 
    path('editar/<int:pk>/', ConsultaUpdateView.as_view(), name='editar_consulta'),
]

contas/urls.py
from django.urls import path, include
from .views import *
from . import views
from funcionarios import urls

app_name = 'contas'

urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register'),
    path('', LoginView.as_view(), name='login'),
    path('profile/', views.user_profile, name='profile'),

]

exames/urls.py
from django.urls import path
from .views import *

app_name = 'exames'

urlpatterns = [
    path('', ListaPedidosView.as_view(), name='lista_pedidos'),
    path('agendar/', CriarPedidoView.as_view(), name='criar_pedido'),
    path('detalhes/<int:pk>/', PedidoDetailView.as_view(), name='detalhes_pedido'),
    path('editar/<int:pk>/', PedidoUpdateView.as_view(), name='editar_pedido'),
]

consultas/forms.py
from django import forms
from .models import *
from pacientes.models import *
from funcionarios.models import *
from procedimentos.models import *
from .models import *



class ConsultaForm(forms.ModelForm):
    class Meta:
        model = Consulta
        fields = ['data', 'hora', 'dentista','paciente', 'procedimentos', 'status']

    paciente = forms.ModelChoiceField(
        queryset = Cliente.objects.all(),
        required = True,
        label = "Paciente"
    )
    
    dentista = forms.ModelChoiceField(
        queryset = Dentista.objects.all(),
        required = True,
        label = "Dentista"
    )

    procedimentos = forms.ModelMultipleChoiceField(
        queryset = Procedimento.objects.all(),
        required = True,
        widget = forms.CheckboxSelectMultiple,
        label = "Procedimentos"
    )

    data = forms.DateField(widget=forms.SelectDateWidget, label="Data")
    hora = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}), label="Hora")
    status = forms.ChoiceField(choices=[('agendada', 'Agendada'), 
                                       ('suspensa', 'Suspensa'), 
                                       ('concluída', 'Concluída')], 
                                        required=True)
    
    def save(self,commit=True):
        consulta=super().save(commit=False)
                
        

        if commit: 
            consulta.save()

            procedimentos_selecionados = self.cleaned_data['procedimentos']
            consulta.procedimentos.set(procedimentos_selecionados)
            
            # ---------- jeito que funciona pra cadastrar n2n--------------------------
            #if 'procedimentos' in self.cleaned_data:
                #procedimentos = self.cleaned_data['procedimentos']
                #consulta.procedimentos.set(procedimentos)  # Associa os procedimentos selecionados à consulta
        return consulta

    def __init__(self, *args, **kwargs):
        # Por mais que não seja usado nesse form, tem que ter isso pra não bugar
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)


class ConsultaFormPaciente(forms.ModelForm):
    class Meta:
        model = Consulta
        fields = ['data', 'hora', 'dentista']

    dentista = forms.ModelChoiceField(
        queryset = Dentista.objects.all(),
        required = True,
        label = "Dentista"
    )

    data = forms.DateField(widget=forms.SelectDateWidget, label="Data")
    hora = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}), label="Hora")

    def save(self,commit=True):
        consulta = super().save(commit=False)
        
        consulta.status = 'agendada'
        consulta.paciente = self.user.cliente

        if commit: 
            consulta.save()

            # Associa o procedimento automaticamente para cliente, deixem um procedimento "Consulta" no bd de vcs
            procedimento_especifico = Procedimento.objects.get(nome="Consulta") 
            consulta.procedimentos.add(procedimento_especifico)
        
        return consulta
    
    def __init__(self, *args, **kwargs):
        # Pega o usuário da view
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

class ConsultaFormPaciente2(forms.ModelForm):
    class Meta:
        model = Consulta
        fields = []
    dentista=forms.HiddenInput
    data = forms.HiddenInput
    hora = forms.HiddenInput
    status = forms.HiddenInput
    paciente = forms.HiddenInput
    procedimentos=forms.HiddenInput
    
    def __init__(self, *args, **kwargs):
        # Pega o usuário da view
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
    

class ConsultaFormDentista(forms.ModelForm):
    class Meta:
        model = Consulta
        fields = ['data', 'hora', 'paciente', 'procedimentos']

    paciente = forms.ModelChoiceField(
        queryset = Cliente.objects.all(),
        required = True,
        label = "Paciente"
    )
    
    procedimentos = forms.ModelMultipleChoiceField(
        queryset = Procedimento.objects.all(),
        required = True,
        widget = forms.CheckboxSelectMultiple,
        label = "Procedimentos"
    )

    data = forms.DateField(widget=forms.SelectDateWidget, label="Data")
    hora = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}), label="Hora")

    def save(self,commit=True):
        consulta = super().save(commit=False)
                
        consulta.status = 'agendada'
        consulta.dentista = self.user.dentista

        if commit: 
            consulta.save()
        
            procedimentos_selecionados = self.cleaned_data['procedimentos']
            for procedimento in procedimentos_selecionados:
                consulta.procedimentos.add(procedimento)

            # consulta.procedimentos.set(procedimentos_selecionados)
            # procedimento_especifico = Procedimento.objects.get(nome="Consulta") 
            # consulta.procedimentos.add(procedimento_especifico)
            
        return consulta
    
    def __init__(self, *args, **kwargs):
        # Pega o usuário da view
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

class ConsultaFormDentista2(forms.ModelForm):
    class Meta:
        model = Consulta
        fields = []
    data = forms.HiddenInput
    hora = forms.HiddenInput
    status = forms.HiddenInput
    paciente = forms.HiddenInput
    procedimentos=forms.HiddenInput

    def __init__(self, *args, **kwargs):
        # Pega o usuário da view
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

consultas/views.py
from django.shortcuts import render,redirect
from django.http import Http404
from django.urls import reverse_lazy,reverse
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from .models import *
from .forms import *
from datetime import time,datetime,timedelta
import locale
import math
from funcionarios.forms import SelecionarDentistaForm
from pacientes.models import Cliente
from django.utils.dateparse import parse_datetime
#locale.setlocale(locale.LC_TIME, 'pt_BR.UTF-8')

def iterar_horarios(data):
    inicio = datetime.combine(data, time(8, 0))  #Início às 08:00
    fim = datetime.combine(data, time(19, 30))  
    horario_atual = inicio
    while horario_atual <= fim:
        yield horario_atual
        horario_atual += timedelta(minutes=30)

class CriarConsultaView(LoginRequiredMixin,PermissionRequiredMixin, CreateView):
    permission_required = 'consultas.add_consulta'
    model = Consulta
    template_name = 'consultas/criar_consulta.html'
    success_url = reverse_lazy('consultas:lista_consultas')

    def get(self, request, pk=None):
        dentista=Dentista.objects.get(id=pk)
        dentistaform=SelecionarDentistaForm()
        form=self.get_form_class()
        calendario = {}
        dia = datetime.today().date()
        for i in range(15):
            if dia.weekday()!=6:
                calendario[dia.strftime('%d/%m (%a)')] = self.gerar_horarios(dia,dentista)
                dia += timedelta(days=1)
            else:
                calendario[dia.strftime('%d/%m (%a)')] = []
                dia += timedelta(days=1)
        return render(request, 'consultas/criar_consulta.html', {'form':form,'dentista':dentista,'calendario':calendario,'dentistaform':dentistaform})
    
    def post(self, request, pk):
        hora_selecionada = request.POST.get('hora')
        form_class = self.get_form_class()
        form = form_class(request.POST, user=request.user)

        if hora_selecionada:
            if form.is_valid():
                # Converte o horário para datetime
                horario = parse_datetime(hora_selecionada)
                dentista = Dentista.objects.get(id=pk)
                consulta = form.save(commit=False)
                consulta.status = 'agendada'
                consulta.paciente = Cliente.objects.get(usuario=self.request.user)
                consulta.dentista = dentista
                consulta.data = horario.date()  # Certifique-se que datahora é um datetime válido
                consulta.hora = horario.time()
                consulta.save()
                procedimento_especifico = Procedimento.objects.get(nome="Consulta") 
                consulta.procedimentos.add(procedimento_especifico)
                consulta.save()
            return redirect(self.success_url)
        else:
            return redirect('consultas:lista_consultas')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        user = self.request.user
        kwargs['user'] = user  # Passando o usuário para o formulário
        return kwargs
    
    def get_form_class(self):
        user = self.request.user
        # Verifica o tipo de usuário e escolhe o formulário correto
        if hasattr(user, 'cliente'):
            return ConsultaFormPaciente2  # Formulário para pacientes
        elif hasattr(user, 'dentista'):
            return ConsultaFormDentista  # Formulário para dentistas
        else:
            return ConsultaForm  # Formulário com todos os campos
        
    def gerar_horarios(self,data,dentista):
        inicio = datetime.combine(data, time(8, 0))  #Início às 08:00
        fim = datetime.combine(data, time(19, 30)) 
        horarios = []
        consultas=Consulta.objects.filter(dentista=dentista.id, data=data)
        restricoes=Restricao.objects.filter(dentista=dentista.id, data=data)
        while inicio <= fim:
            if restricoes:
                for restricao in restricoes:
                    inicio_dt = datetime.combine(data, inicio.time())  # Combina com a data atual
                    restricao_dt = datetime.combine(data, restricao.hora_inicio)  # O mesmo para a hora de restrição
                    # Calcula a diferença
                    diferenca = abs(inicio_dt - restricao_dt)
                    if inicio.time()==restricao.hora_inicio or (diferenca <= timedelta(minutes=15)):
                        inicio += abs(datetime.combine(data, restricao.hora_inicio)-datetime.combine(data,restricao.hora_fim))
            if consultas:
                for consulta in (consultas):
                    if inicio.time()!=consulta.hora:
                        horarios.append(inicio)
                        inicio += timedelta(minutes=30)       
                    else:
                        procedimentosConsulta=consulta.procedimentos.all()
                        if procedimentosConsulta:
                            duracao_total = sum([proc.duracao_media.total_seconds() for proc in procedimentosConsulta])
                            duracao_arredondada = math.ceil(duracao_total / (15 * 60)) * 15 * 60
                            inicio += timedelta(seconds=duracao_arredondada)
                        else:
                            inicio += timedelta(minutes=30)   

            else:
                horarios.append(inicio)
                inicio += timedelta(minutes=30)
        return horarios
  
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class ConsultaUpdateView(LoginRequiredMixin, PermissionRequiredMixin,UpdateView):
    permission_required = 'consultas.change_consulta'
    model = Consulta
    form_class = ConsultaForm
    template_name = 'consultas/edita_consulta.html'
    success_url = reverse_lazy('consultas:lista_consultas')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        user = self.request.user
        kwargs['user'] = user  # Passando o usuário para o formulário
        return kwargs

    def get_object(self, queryset=None):
        # Obtém a consulta que será editada
        obj = super().get_object(queryset)

        # Verifica se o usuário tem permissão para editar a consulta
        if self.request.user == obj.paciente:
            raise Http404("Você não tem permissão para editar esta consulta")
        
        return obj
 
class ListaConsultasView(LoginRequiredMixin,PermissionRequiredMixin, ListView):
    permission_required = 'consultas.view_consulta'
    model = Consulta
    template_name = 'consultas/lista_consultas.html'
    context_object_name = 'consultas'

    def get_queryset(self):
        user = self.request.user

        
        if user.tipo_usuario == 'client':
            # Se for paciente, exibe somente suas consultas
            return Consulta.objects.filter(paciente=user.cliente).order_by('-data','-hora')
        
        elif user.tipo_usuario == 'dentist':
            # Se for dentista, exibe as consultas onde ele é o dentista
            return Consulta.objects.filter(dentista=user.dentista).order_by('-data','-hora')

        # Caso seja admin ou secretario, exibe todas as consultas
        return Consulta.objects.all()
    
class ConsultaDetailView(LoginRequiredMixin, PermissionRequiredMixin,DetailView):
    permission_required = 'consultas.view_consulta'
    model = Consulta
    template_name = 'consultas/detalhes_consulta.html'
    context_object_name = 'consulta'

def SelecionaDentistaView(request):
    if request.method == 'GET':
        try:
            form = SelecionarDentistaForm(request.GET)
            if form.is_valid():
                pk = form.cleaned_data['dentista'].id
                return redirect('consultas:criar_consulta', pk=pk)
            else:
                dentista=Dentista.objects.first()
                return redirect('consultas:criar_consulta', pk=dentista.id)
        except:
            dentista=Dentista.objects.first()
            return redirect('consultas:criar_consulta', pk=dentista.id)

class CriarConsultaDentistaView(LoginRequiredMixin,PermissionRequiredMixin, CreateView):
    permission_required = 'consultas.add_consulta'
    model = Consulta
    template_name = 'consultas/criar_consultaDentista.html'
    success_url = reverse_lazy('consultas:lista_consultas')

    def get(self, request, pk=None):
        cliente=Cliente.objects.get(id=pk)
        dentista=Dentista.objects.get(usuario=self.request.user)
        #dentistaform=SelecionarDentistaForm()
        form=self.get_form_class()
        calendario = {}
        dia = datetime.today().date()
        for i in range(15):
            if dia.weekday()!=6:
                calendario[dia.strftime('%d/%m (%a)')] = self.gerar_horarios(dia,dentista)
                dia += timedelta(days=1)
            else:
                calendario[dia.strftime('%d/%m (%a)')] = []
                dia += timedelta(days=1)
        return render(request, 'consultas/criar_consultaDentista.html', {'form':form,'dentista':dentista,'calendario':calendario,'cliente':cliente})
    
    def post(self, request, pk):
        hora_selecionada = request.POST.get('hora')
        form_class = self.get_form_class()
        form = form_class(request.POST, user=request.user)

        if hora_selecionada:
            if form.is_valid():
                # Converte o horário para datetime
                horario = parse_datetime(hora_selecionada)
                cliente = Cliente.objects.get(id=pk)
                consulta = form.save(commit=False)
                consulta.status = 'agendada'
                consulta.paciente = cliente
                consulta.dentista = Dentista.objects.get(usuario=self.request.user)
                consulta.data = horario.date()  # Certifique-se que datahora é um datetime válido
                consulta.hora = horario.time()
                consulta.save()

consultas/templates/consultas/calendarioPietro.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Criar Consulta{% endblock title %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calendário Mensal</title>
    <link rel="stylesheet" href="{% static 'calendario.css' %}">
</head>

<body>
    <main>

    <h1>Criar Consulta</h1>

    <div class="calendar-container">
        <div class="calendar-header">
            <button id="prev-month">◀</button>
            <h2 id="current-month">Janeiro 2024</h2>
            <button id="next-month">▶</button>
        </div>

        <div class="calendar">
            <div class="days-header">
                <span>Dom</span>
                <span>Seg</span>
                <span>Ter</span>
                <span>Qua</span>
                <span>Qui</span>
                <span>Sex</span>
                <span>Sáb</span>
            </div>
            <div class="days-grid" id="days-grid"></div>
        </div>
    </div>

    <div class="agenda-modal" id="agenda-modal">
        <div class="agenda-content">
            <h3 id="selected-date">Dia 1</h3>
            <ul id="agenda-list">
                <!-- Horários serão gerados dinamicamente -->
            </ul>
        </div>
    </div>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Agendar Consulta</button>
    </form>

    <script src="{% static 'calendario.js' %}"></script>
    </main>
</body>

{% endblock %}

consultas/templates/consultas/criar_consulta.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Criar Consulta{% endblock %}

{% block content %}
<h1 style="margin-bottom: 0;">Agendar Consulta</h1>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        const track = document.querySelector('.carousel-track');
        const cards = Array.from(document.querySelectorAll('.carousel-card'));
        const leftButton = document.querySelector('.left-btn');
        const rightButton = document.querySelector('.right-btn');
    
        const cardWidth = cards[0].getBoundingClientRect().width;
        const visibleCards = 5;
        let currentPosition = 0;
    
        function updateButtons() {
            leftButton.disabled = currentPosition === 0;
            rightButton.disabled = currentPosition >= cards.length - visibleCards;
        }
    
        function moveCarousel(offset) {
            currentPosition += offset;
            track.style.transform = `translateX(-${currentPosition * cardWidth}px)`;
            updateButtons();
        }
    
        leftButton.addEventListener('click', () => moveCarousel(-1));
        rightButton.addEventListener('click', () => moveCarousel(1));
    
        updateButtons(); // Inicializa os botões
    });
</script>
    
<style>
    .carousel-container {
        display: flex;
        align-items: center;
        position: relative;
        overflow: hidden;
        width: 100%;
         /* max-width: 800px; Limite de largura */
        margin: 0 auto;
    }
    
    .carousel-track {
        display: flex;
        transition: transform 0.5s ease;
        width: fit-content;
    }
    
    .carousel-card {
       
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        padding: 10px;
        margin: 0 10px;
        background: linear-gradient(to bottom, #08a8f2, #0cb9de);
        border-radius: 8px;
        text-align: center;
    }
    
    .carousel-btn {
        background-color: #007bff;
        color: white;
        border: none;
        padding: 10px;
        cursor: pointer;
        position: absolute;
        top: 50%;
        transform: translateY(-50%);
        z-index: 2;
        font-size: 16px;
        border-radius: 50%;
    }
    
    .left-btn {
        left: 10px;
    }
    
    .right-btn {
        right: 10px;
    }
    
    .carousel-btn:disabled {
        background-color: #ccc;
        cursor: not-allowed;
    }
    </style>
    
{% if calendario %}
<div class="calendarioCabecalho">
    <h3 style="float:left ">Dentista: {{ dentista }}</h3>
    <form method="get" action="{% url 'consultas:selecionaDentista' %}">
        {% csrf_token %}
        {{ dentistaform.as_p }}
        <button type="submit" style="float:left ">Selecionar</button>
    </form>
</div>
<section style="float: none;">
    <div class="carousel-container">
        <button class="carousel-btn left-btn">&larr;</button>
        <div class="carousel-track">
            {% for dia, horarios in calendario.items %}
                <article class="carousel-card">
                    <strong>{{ dia }}</strong>
                    <ul class="listaHorarios">
                        {% if horarios  %}
                            {% for horario in horarios %}
                            <li>
                                <form method="post">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <input type="hidden" name="hora" value="{{ horario|date:"Y-m-d H:i:s" }}">
                                    <button type="submit" style="background: none; border: none; color: #fff; cursor: pointer;">{{ horario|date:"H:i" }}</button>
                                </form>
                            </li>
                            {% endfor %}
                        {% else %}
                            <p>Fechado</p>
                        {% endif %}
                    </ul>
                </article>
            {% endfor %}
        </div>
        <button class="carousel-btn right-btn">&rarr;</button>
    </div>
</section>
{% else %}
    <p>Não foi possível carregar</p>
{% endif %}


    <script src="{% static 'calendario.js' %}"></script>
    </main>
</body>
{% endblock %}

consultas/templates/consultas/criar_consultaDentista.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Criar Consulta{% endblock %}

{% block content %}
<h1>Criar Consulta para {{ cliente.nome }}</h1>


<script>
    document.addEventListener('DOMContentLoaded', () => {
        const track = document.querySelector('.carousel-track');
        const cards = Array.from(document.querySelectorAll('.carousel-card'));
        const leftButton = document.querySelector('.left-btn');
        const rightButton = document.querySelector('.right-btn');
    
        const cardWidth = cards[0].getBoundingClientRect().width;
        const visibleCards = 5;
        let currentPosition = 0;
    
        function updateButtons() {
            leftButton.disabled = currentPosition === 0;
            rightButton.disabled = currentPosition >= cards.length - visibleCards;
        }
    
        function moveCarousel(offset) {
            currentPosition += offset;
            track.style.transform = `translateX(-${currentPosition * cardWidth}px)`;
            updateButtons();
        }
    
        leftButton.addEventListener('click', () => moveCarousel(-1));
        rightButton.addEventListener('click', () => moveCarousel(1));
    
        updateButtons(); // Inicializa os botões
    });
</script>
    
<style>
    .carousel-container {
        display: flex;
        align-items: center;
        position: relative;
        overflow: hidden;
        width: 100%;
         /* max-width: 800px; Limite de largura */
        margin: 0 auto;
    }
    
    .carousel-track {
        display: flex;
        transition: transform 0.5s ease;
        width: fit-content;
    }
    
    .carousel-card {
       
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        padding: 10px;
        margin: 0 10px;
        background: linear-gradient(to bottom, #08a8f2, #0cb9de);
        border-radius: 8px;
        text-align: center;
    }
    
    .carousel-btn {
        background-color: #007bff;
        color: white;
        border: none;
        padding: 10px;
        cursor: pointer;
        position: absolute;
        top: 50%;
        transform: translateY(-50%);
        z-index: 2;
        font-size: 16px;
        border-radius: 50%;
    }
    
    .left-btn {
        left: 10px;
    }
    
    .right-btn {
        right: 10px;
    }
    
    .carousel-btn:disabled {
        background-color: #ccc;
        cursor: not-allowed;
    }
    </style>
    
{% if calendario %}
<section style="float: none;">
    <h1 class="calendarioCabecalho">Selecione um horário</h1>
    <div class="carousel-container">
        <button class="carousel-btn left-btn">&larr;</button>
        <div class="carousel-track">
            {% for dia, horarios in calendario.items %}
                <article class="carousel-card">
                    <strong>{{ dia }}</strong>
                    <ul class="listaHorarios">
                        {% if horarios  %}
                            {% for horario in horarios %}
                                <li>
                                    <form method="post">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <input type="hidden" name="hora" value="{{ horario|date:"Y-m-d H:i:s" }}">
                                        <button type="submit" style="background: none; border: none; color: #fff; cursor: pointer;">{{ horario|date:"H:i" }}</button>
                                    </form>
                            </li>
                            {% endfor %}
                        {% else %}
                            <p>Fechado</p>
                        {% endif %}
                    </ul>
                </article>
            {% endfor %}
        </div>
        <button class="carousel-btn right-btn">&rarr;</button>
    </div>
</section>
{% else %}
    <p>Não foi possível carregar</p>
{% endif %}


    <script src="{% static 'calendario.js' %}"></script>
    </main>
</body>
{% endblock %}

consultas/templates/consultas/detalhes_consulta.html
{% extends 'base.html' %}

{% block content %}
    <h2>Detalhes da Consulta</h2>
    
    <p><strong>Paciente:</strong> {{ consulta.paciente }}</p>
    <p><strong>Dentista:</strong> {{ consulta.dentista }}</p>
    <p><strong>Data:</strong> {{ consulta.data }}</p>
    <p><strong>Hora:</strong> {{ consulta.hora }}</p>
    <p><strong>Status:</strong> {{ consulta.status }}</p>
    
    <h3>Procedimentos Realizados:</h3>
    <ul>
        {% for procedimento in consulta.procedimentos.all %}
            <li>{{ procedimento.nome }} - {{ procedimento.descricao }}</li>
        {% endfor %}
    </ul>
    
    {% if user.cliente != consulta.paciente %}
        <a href="{% url 'consultas:editar_consulta' pk=consulta.pk %}">
            <button>Editar Consulta</button>
        </a>
    {% endif %}

    <a href="{% url 'consultas:lista_consultas' %}">Voltar para a lista de consultas</a>

    {% endblock %}

consultas/templates/consultas/edita_consulta.html
{% extends 'base.html' %}

{% block content %}
  <h2>Editar Consulta</h2>
  
  <form method="post" class="formClass">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar alterações</button>
  </form>
  
  <a href="{% url 'consultas:lista_consultas' %}">Voltar para a lista de consultas</a>
{% endblock %}

consultas/templates/consultas/lista_consultas.html
{% extends 'base.html' %}

{% block content %}
    <h1>Consultas</h1>

    {% if consultas %}
        <table  class="consulta-table">
            <thead>
                <tr>
                    <th>Data</th>
                    <th>Hora</th>
                    <th>Status</th>
                    <th>Paciente</th>
                    <th>Dentista</th>
                    <th>Procedimentos</th>
                </tr>
            </thead>
            <tbody>
                {% for consulta in consultas %}
                    <tr>
                        <td>{{ consulta.data }}</td>
                        <td>{{ consulta.hora }}</td>
                        <td>{{ consulta.status }}</td>
                        <td>{{ consulta.paciente.nome }}</td>
                        <td>{{ consulta.dentista.nome }}</td>
                        <td>
                            
                            <a href="{% url 'consultas:detalhes_consulta' consulta.id %}">Ver Detalhes</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Não há consultas agendadas.</p>
    {% endif %}

    <a href="{% url 'contas:profile' %}">Voltar para página inicial</a>
{% endblock %}

consultas/templates/consultas/nav.html
{% load static %}

{% if user.tipo_usuario == 'dentist' and cliente %}
<nav>
    <a href="{% url 'consultas:Dentistacriar_consulta' cliente.id %}">Agendar uma consulta</a>
    <a href="{% url 'exames:lista_pedidos' %}">Seus pedidos de exames</a>
</nav>

{% elif user.tipo_usuario == 'client' %}
<nav>
    <a href="{% url 'consultas:selecionaDentista' %}">Agendar uma consulta</a>
    <a href="{% url 'exames:lista_pedidos' %}">Seus pedidos de exames</a>
</nav>
{% endif %}