Odontech/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('', include('staticpages.urls')),
    path("admin/", admin.site.urls),
    path('', include('contas.urls')),
    path('funcionarios/', include('funcionarios.urls')),
    path('consultas/', include('consultas.urls')),
    path('exames/', include('exames.urls')),
    path('procedimentos/', include('procedimentos.urls')),
    path('pacientes/', include('pacientes.urls')),
    path('', include('django.contrib.auth.urls')),
]

consultas/urls.py
from django.urls import path
from .views import *

app_name = 'consultas'

urlpatterns = [
    path('', ListaConsultasView.as_view(), name='lista_consultas'),
    path('agendar/<int:pk>/dentista/', CriarConsultaDentistaView.as_view(), name='Dentistacriar_consulta'),
    path('agendar/<int:pk>/', CriarConsultaView.as_view(), name='criar_consulta'),
    path('agendar/selecionaDent/', SelecionaDentistaView, name='selecionaDentista'),
    path('detalhes/<int:pk>/', ConsultaDetailView.as_view(), name='detalhes_consulta'), 
    path('editar/<int:pk>/', ConsultaUpdateView.as_view(), name='editar_consulta'),
]

contas/urls.py
from django.urls import path, include
from .views import *
from . import views
from funcionarios import urls

app_name = 'contas'

urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register'),
    path('', LoginView.as_view(), name='login'),
    path('profile/', views.user_profile, name='profile'),

]

exames/urls.py
from django.urls import path
from .views import *

app_name = 'exames'

urlpatterns = [
    path('', ListaPedidosView.as_view(), name='lista_pedidos'),
    path('agendar/', CriarPedidoView.as_view(), name='criar_pedido'),
    path('detalhes/<int:pk>/', PedidoDetailView.as_view(), name='detalhes_pedido'),
    path('editar/<int:pk>/', PedidoUpdateView.as_view(), name='editar_pedido'),
]

exames/models.py
from django.db import models
from pacientes.models import Cliente
from funcionarios.models import Dentista


class Exame(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField()
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    custo = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.nome

class Pedido(models.Model):
    dentista = models.ForeignKey(Dentista, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    data = models.DateField()
    status = models.CharField(max_length=20)
    link_resultado = models.URLField(null=True, blank=True)
    exames=models.ManyToManyField(Exame)

exames/forms.py
from django import forms
from .models import *
from pacientes.models import Cliente
from funcionarios.models import Dentista


class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['data', 'cliente', 'dentista', 'exames', 'status']

    cliente = forms.ModelChoiceField(
        queryset = Cliente.objects.all(), 
        required = True,
        label = "Paciente")
    
    dentista = forms.ModelChoiceField(
        queryset = Dentista.objects.all(), 
        required = True,
        label = "Dentista")
    
    exames = forms.ModelMultipleChoiceField(
        queryset = Exame.objects.all(), 
        required = True, 
        widget = forms.CheckboxSelectMultiple,
        label = "Exames")

    data = forms.DateField(widget=forms.SelectDateWidget)
    status = forms.ChoiceField(choices=[('pendente', 'Pendente'), 
                                        ('realizado', 'Realizado')], 
                                        required=True)
    
    def save(self,commit=True):
        pedido = super().save(commit=False)
                
        

        if commit: 
            pedido.save()

            exames_selecionados = self.cleaned_data['exames']
            pedido.exames.set(exames_selecionados)

        return pedido
    
    def __init__(self, *args, **kwargs):
        # Pega o usuário da view
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)


class PedidoFormDentista(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['data', 'cliente', 'exames']

    cliente = forms.ModelChoiceField(
        queryset = Cliente.objects.all(), 
        required = True,
        label = "Paciente")
    
    exames = forms.ModelMultipleChoiceField(
        queryset = Exame.objects.all(), 
        required = True, 
        widget = forms.CheckboxSelectMultiple,
        label = "Exames")

    data = forms.DateField(widget=forms.SelectDateWidget)
    
    def save(self,commit=True):
        pedido=super().save(commit=False)
                
        pedido.status = 'pendente'
        pedido.dentista = self.user.dentista
        
        if commit: 
            pedido.save()

            exames_selecionados = self.cleaned_data['exames']
            pedido.exames.set(exames_selecionados)

        return pedido
    
    def __init__(self, *args, **kwargs):
        # Pega o usuário da view
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

class UpdatePedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['data', 'cliente', 'dentista', 'exames', 'status', 'link_resultado']

    cliente = forms.ModelChoiceField(
        queryset = Cliente.objects.all(), 
        required = True,
        label = "Paciente")
    
    dentista = forms.ModelChoiceField(
        queryset = Dentista.objects.all(), 
        required = True,
        label = "Dentista")
    
    exames = forms.ModelMultipleChoiceField(
        queryset = Exame.objects.all(), 
        required = True, 
        widget = forms.CheckboxSelectMultiple,
        label = "Exames")

    data = forms.DateField(widget=forms.SelectDateWidget)
    status = forms.ChoiceField(choices=[('pendente', 'Pendente'), 
                                        ('realizado', 'Realizado')], 
                                        required=True)
    
    link_resultado = forms.URLField(
        required=False, 
        label="Link do Resultado", 
        widget=forms.URLInput(attrs={'placeholder': 'Informe o link do resultado'}),
        initial=""  # Opcional: Você pode definir um valor inicial, caso o pedido já tenha link de resultado.
    )

    def save(self, commit=True):
        pedido = super().save(commit=False)
        
        if commit:
            pedido.save()
            exames_selecionados = self.cleaned_data['exames']
            pedido.exames.set(exames_selecionados)
        
        return pedido
    
    def __init__(self, *args, **kwargs):
        # Pega o usuário da view
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

exames/views.py
from django.shortcuts import render
from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from .models import *
from .forms import *


class CriarPedidoView(LoginRequiredMixin,PermissionRequiredMixin, CreateView):
    permission_required = 'exames.add_pedido'
    model = Pedido
    template_name = 'exames/criar_pedido.html'
    success_url = reverse_lazy('exames:lista_pedidos')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        user = self.request.user
        
        kwargs['user'] = user  # Passando o usuário para o formulário
        
        return kwargs
    
    def get_form_class(self):
        user = self.request.user

        # Verifica o tipo de usuário e escolhe o formulário correto
        if hasattr(user, 'dentista'):
            return PedidoFormDentista  # Formulário para dentistas
        
        else:
            return PedidoForm  # Formulário com todos os campos


class PedidoUpdateView(LoginRequiredMixin, PermissionRequiredMixin,UpdateView):
    permission_required = 'exames.change_pedido'
    model = Pedido
    form_class = UpdatePedidoForm
    template_name = 'exames/editar_pedido.html'
    success_url = reverse_lazy('exames:lista_pedidos')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        user = self.request.user
        kwargs['user'] = user  # Passando o usuário para o formulário
        return kwargs

    def get_object(self, queryset=None):
        # Obtém a consulta que será editada
        obj = super().get_object(queryset)

        # Verifica se o usuário tem permissão para editar a consulta
        if self.request.user == obj.cliente:
            raise Http404("Você não tem permissão para editar este pedido")
        
        return obj


class ListaPedidosView(LoginRequiredMixin,PermissionRequiredMixin, ListView):
    permission_required = 'exames.view_pedido'
    model = Pedido
    template_name = 'exames/lista_pedidos.html'
    context_object_name = 'pedidos'

    def get_queryset(self):
        user = self.request.user
        
        if user.tipo_usuario == 'client':
            # Se for paciente, exibe somente seus pedidos de exames
            return Pedido.objects.filter(cliente=user.cliente)
        
        elif user.tipo_usuario == 'dentist':
            # Se for dentista, exibe os pedidos em que ele é o dentista
            return Pedido.objects.filter(dentista=user.dentista)

        # Caso seja admin ou secretario, exibe todos os pedidos
        return Pedido.objects.all()
    

class PedidoDetailView(LoginRequiredMixin, PermissionRequiredMixin,DetailView):
    permission_required = 'exames.view_pedido'
    model = Pedido
    template_name = 'exames/detalhes_pedido.html'
    context_object_name = 'pedido'

exames/templates/exames/criar_pedido.html
{% extends 'base.html' %}

{% block content %}
  <h2>Criar Pedido de Exame</h2>
  <form method="post" class="formClass">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
  </form>
{% endblock %}

exames/templates/exames/detalhes_pedido.html
{% extends 'base.html' %}

{% block content %}
  <h2>Detalhes do Pedido de Exame</h2>
  
  <p><strong>Cliente:</strong> {{ pedido.cliente }}</p>
  <p><strong>Dentista:</strong> {{ pedido.dentista }}</p>
  <p><strong>Data:</strong> {{ pedido.data }}</p>
  <p><strong>Status:</strong> {{ pedido.status }}</p>
  
  <h3>Exames Solicitados:</h3>
  <ul>
    {% for exame in pedido.exames.all %}
      <li>{{ exame.nome }} - {{ exame.descricao }}</li>
    {% endfor %}
  </ul>
  
  <p><strong>Resultado:</strong> 
    {% if pedido.link_resultado %}
      <a href="{{ pedido.link_resultado }}" target="_blank">Ver Resultado</a>
    {% else %}
      Não disponível
    {% endif %}
  </p>

  {% if user.cliente != pedido.cliente %}
    <a href="{% url 'exames:editar_pedido' pk=pedido.pk %}">
      <button>Editar Pedido</button>
    </a>
  {% endif %}

  <a href="{% url 'exames:lista_pedidos' %}">Voltar para a lista de pedidos</a>
{% endblock %}

exames/templates/exames/editar_pedido.html
{% extends 'base.html' %}

{% block content %}
  <h2>Editar Pedido de Exame</h2>
  
  <form method="post" class="formClass">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
  </form>

  <a href="{% url 'exames:lista_pedidos' %}">Voltar para a lista de pedidos</a>
{% endblock %}

exames/templates/exames/lista_pedidos.html
{% extends 'base.html' %}

{% block content %}
  <h2>Lista de Pedidos de Exames</h2>
  <table class="consulta-table">
    <thead>
      <tr>
        <th>Cliente</th>
        <th>Dentista</th>
        <th>Data</th>
        <th>Status</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for pedido in pedidos %}
        <tr>
          <td>{{ pedido.cliente }}</td>
          <td>{{ pedido.dentista }}</td>
          <td>{{ pedido.data }}</td>
          <td>{{ pedido.status }}</td>
          <td><a href="{% url 'exames:detalhes_pedido' pedido.id%}">Detalhes</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <a href="{% url 'contas:profile' %}">Voltar para página inicial</a>
{% endblock %}

exames/templates/exames/nav.html
{% load static %}
<nav>
    <a href="{% url 'consultas:lista_consultas' %}">Suas consultas</a>
    {% if user.tipo_usuario != 'client' %}
        <a href="{% url 'exames:criar_pedido' %}">Pedir exame</a>
    {% endif %}
    
</nav>