Odontech/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('', include('staticpages.urls')),
    path("admin/", admin.site.urls),
    path('', include('contas.urls')),
    path('funcionarios/', include('funcionarios.urls')),
    path('consultas/', include('consultas.urls')),
    path('exames/', include('exames.urls')),
    path('procedimentos/', include('procedimentos.urls')),
    path('pacientes/', include('pacientes.urls')),
    path('', include('django.contrib.auth.urls')),
]

consultas/urls.py
from django.urls import path
from .views import *

app_name = 'consultas'

urlpatterns = [
    path('', ListaConsultasView.as_view(), name='lista_consultas'),
    path('agendar/<int:pk>/dentista/', CriarConsultaDentistaView.as_view(), name='Dentistacriar_consulta'),
    path('agendar/<int:pk>/', CriarConsultaView.as_view(), name='criar_consulta'),
    path('agendar/selecionaDent/', SelecionaDentistaView, name='selecionaDentista'),
    path('detalhes/<int:pk>/', ConsultaDetailView.as_view(), name='detalhes_consulta'), 
    path('editar/<int:pk>/', ConsultaUpdateView.as_view(), name='editar_consulta'),
]

contas/urls.py
from django.urls import path, include
from .views import *
from . import views
from funcionarios import urls

app_name = 'contas'

urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register'),
    path('', LoginView.as_view(), name='login'),
    path('profile/', views.user_profile, name='profile'),

]

exames/urls.py
from django.urls import path
from .views import *

app_name = 'exames'

urlpatterns = [
    path('', ListaPedidosView.as_view(), name='lista_pedidos'),
    path('agendar/', CriarPedidoView.as_view(), name='criar_pedido'),
    path('detalhes/<int:pk>/', PedidoDetailView.as_view(), name='detalhes_pedido'),
    path('editar/<int:pk>/', PedidoUpdateView.as_view(), name='editar_pedido'),
]

funcionarios/urls.py
from django.urls import path
from . import views

app_name = 'funcionarios'
urlpatterns = [
    path('dentista/', views.ListDentista.as_view(), name='indexDentista'),
    path('dentista/<int:pk>/', views.DetailDentista.as_view(), name='detailDentista'),
    path('dentista/horario/<int:pk>/', views.CreateRestricaoDentista.as_view(), name='horarioDentista'),
    path('dentista/horario/<int:pk>/delete/', views.DeleteRestricao.as_view(), name='deleteRestricao'),
    path('dentista/update/<int:pk>/', views.UpdateDentista.as_view(), name='updateDentista'),
    path('dentista/delete/<int:pk>/', views.DeleteDentista.as_view(), name='deleteDentista'),
    path('dentista/create/', views.CreateUserDentista.as_view(), name='createUserDentista'),
    path('dentista/search/', views.searchDentista, name='searchDentista'),
    path('secretaria/', views.ListSecretario.as_view(), name='indexSecretario'),
    path('secretaria/<int:pk>/', views.DetailSecretario.as_view(), name='detailSecretario'),
    path('secretaria/update/<int:pk>/', views.UpdateSecretario.as_view(), name='updateSecretario'),
    path('secretaria/delete/<int:pk>/', views.DeleteSecretario.as_view(), name='deleteSecretario'),
    path('secretaria/create/', views.CreateUserSecretario.as_view(), name='createUserSecretario'),
    path('secretaria/search/', views.searchSecretario, name='searchSecretario'),
    #path('search/', views.search_post, name='search'),
    #path('<int:pk>/comment/', views.CommentCreateView.as_view(), name='comment'),
    #path('category/', views.categoryListView.as_view(), name='categoryList'),
    #path('cetegory/<int:pk>/', views.categoryDetailView.as_view(), name='categoryDetail'),
]

pacientes/urls.py
from django.urls import path
from . import views

app_name = 'pacientes'
urlpatterns = [
    path('<int:pk>/', views.DetailCliente.as_view(), name='detailCliente'),
    path('update/<int:pk>/', views.UpdateCliente.as_view(), name='updateCliente'),
    path('search/', views.searchCliente, name='searchCliente'),
    path('', views.ListCliente.as_view(), name='listCliente')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="GABRIEL NEGREIROS, NICOLAS SOBRAL CRUZ, PIETRO DI BEO, PIETRO LUIGI BALDAN CARBONE">
	<meta name="description" content="Trabalho apresentado a disciplina de Sistemas de Informação da Escola Politécnica da Universidade de São Paulo">
	<meta name="keywords" content="">
	<meta name="robots" content="index, follow">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}"> 
	<link rel="shortcut icon" href="{% static 'favicon.png' %}">
    <title>{% block title %}{% endblock %} | Odontech</title>
</head>
<body>
   <header class="fixed-top">

        {% include 'menu_deslizante.html' %} <!--  Ver menu_delizante.html -->
        
        <!-- Incluir o menu de navegação específico do app -->
        {% if request.resolver_match.app_name == 'consultas' or request.resolver_match.app_name == 'exames' or request.resolver_match.app_name == 'contas' %}
            {% with nav_path=request.resolver_match.app_name|add:'/nav.html' %}
                {% include nav_path %}
            {% endwith %}
        {% else %}
        
        {% endif %}


        <h1>Odontech</h1>

        <div class="dados-usuario">
            {% if user.is_authenticated %}
                <li>{{ user }}</li>
                <li>
                    <a href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" style="color: aliceblue;">Logout</a>
                    <form id="logout-form" action="{% url 'logout' %}" method="post" style="display: none;">
                        {% csrf_token %}
                    </form>
                </li>
            {% else %}
                <li><a href="{% url 'login' %}">Log in</a></li>
            {% endif %}
        </div>
    </header>

    <main>
        {% block content %}{% endblock content %}
        <script src="{% static 'header.js' %}"></script>
    </main>

    <footer>
        {% block footer %}
        {% endblock footer %}
    </footer>

</body>
</html>

templates/menu_deslizante.html
{% load static %}

<div class="menu-container">

    <button class="botao-menu" onclick="openMenu()" aria-label="Abrir menu">
        <img src="{% static 'icone_menu.png' %}" alt="Ícone do menu">
    </button>
    
    <div id="overlay" class="overlay" onclick="closeMenu()"></div>
    
    {% if user.tipo_usuario == 'admin' %}
        <div id="sidebar" class="sidebar">
            <a href="{% url 'contas:profile' %}">Início</a>
            <a href="{% url 'pacientes:listCliente' %}">Pacientes</a>
            <a href="{% url 'funcionarios:indexDentista' %}">Dentistas</a>
            <a href="{% url 'funcionarios:indexSecretario' %}">Secretários</a>
        </div>

    {% elif user.tipo_usuario == 'dentist' %}
        <div id="sidebar" class="sidebar">
            <a href="{% url 'contas:profile' %}">Início</a>
            <a href="{% url 'pacientes:listCliente' %}">Pacientes</a>
            <a href="{% url 'funcionarios:detailDentista' user.dentista.id %}">Perfil</a>            
        </div>

    {% elif user.tipo_usuario == 'secretary' %}
        <div id="sidebar" class="sidebar">
            <a href="{% url 'contas:profile' %}">Início</a>
            <a href="{% url 'pacientes:listCliente' %}">Pacientes</a>
            <a href="{% url 'funcionarios:indexDentista' %}">Dentistas</a>
            <a href="{% url 'funcionarios:detailSecretario' user.secretario.id %}">Perfil</a>
        </div>
        
    {% elif user.tipo_usuario == 'client' %}
        <div id="sidebar" class="sidebar">
            <a href="{% url 'contas:profile' %}">Início</a>
            <a href="{% url 'consultas:lista_consultas' %}">Suas Consultas</a>
            <a href="{% url 'exames:lista_pedidos' %}">Seus pedidos de exames</a>
            {% if user.is_authenticated %}
            <a href="{% url 'pacientes:detailCliente' user.cliente.id %}">Perfil</a>
            {% endif%}
        </div>

    {% elif user.is_authenticated %}
        <div id="sidebar" class="sidebar">
            <a href="{% url 'contas:profile' %}">Início</a>
            <a href="{% url 'pacientes:listCliente' %}">Pacientes</a>
            <a href="{% url 'funcionarios:indexDentista' %}">Dentistas</a>
            <a href="{% url 'funcionarios:indexSecretario' %}">Secretários</a>
        </div>
    {% endif%}

</div>