Odontech/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('', include('staticpages.urls')),
    path("admin/", admin.site.urls),
    path('', include('contas.urls')),
    path('funcionarios/', include('funcionarios.urls')),
    path('consultas/', include('consultas.urls')),
    path('exames/', include('exames.urls')),
    path('procedimentos/', include('procedimentos.urls')),
    path('pacientes/', include('pacientes.urls')),
    path('', include('django.contrib.auth.urls')),
]

contas/urls.py
from django.urls import path, include
from .views import *
from . import views
from funcionarios import urls

app_name = 'contas'

urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register'),
    path('', LoginView.as_view(), name='login'),
    path('profile/', views.user_profile, name='profile'),

]

funcionarios/urls.py
from django.urls import path
from . import views

app_name = 'funcionarios'
urlpatterns = [
    path('dentista/', views.ListDentista.as_view(), name='indexDentista'),
    path('dentista/<int:pk>/', views.DetailDentista.as_view(), name='detailDentista'),
    path('dentista/horario/<int:pk>/', views.CreateRestricaoDentista.as_view(), name='horarioDentista'),
    path('dentista/horario/<int:pk>/delete/', views.DeleteRestricao.as_view(), name='deleteRestricao'),
    path('dentista/update/<int:pk>/', views.UpdateDentista.as_view(), name='updateDentista'),
    path('dentista/delete/<int:pk>/', views.DeleteDentista.as_view(), name='deleteDentista'),
    path('dentista/create/', views.CreateUserDentista.as_view(), name='createUserDentista'),
    path('dentista/search/', views.searchDentista, name='searchDentista'),
    path('secretaria/', views.ListSecretario.as_view(), name='indexSecretario'),
    path('secretaria/<int:pk>/', views.DetailSecretario.as_view(), name='detailSecretario'),
    path('secretaria/update/<int:pk>/', views.UpdateSecretario.as_view(), name='updateSecretario'),
    path('secretaria/delete/<int:pk>/', views.DeleteSecretario.as_view(), name='deleteSecretario'),
    path('secretaria/create/', views.CreateUserSecretario.as_view(), name='createUserSecretario'),
    path('secretaria/search/', views.searchSecretario, name='searchSecretario'),
    #path('search/', views.search_post, name='search'),
    #path('<int:pk>/comment/', views.CommentCreateView.as_view(), name='comment'),
    #path('category/', views.categoryListView.as_view(), name='categoryList'),
    #path('cetegory/<int:pk>/', views.categoryDetailView.as_view(), name='categoryDetail'),
]

funcionarios/forms.py
from django.forms import ModelForm
from django import forms
from .models import Dentista,Secretario
from django.contrib.auth import get_user_model
from consultas.models import Restricao
from django.contrib.auth.models import Group, Permission

User = get_user_model()

class UserDentistaRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['first_name',
                  'last_name',
                  'email',
                  'password',
                  'confirm_password'
        ]

        labels = {'first_name':"Nome",
                'last_name':"Sobrenome",
                'email':"Email", 
                'password':"Senha",
                'confirm_password':"Confirmar senha"
        }

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password != confirm_password:
            raise forms.ValidationError("As senhas não coincidem.")
        
    def save(form,commit=True):
        userdentista=super().save(commit=False) 
        userdentista.tipo_usuario= 'dentist'
        userdentista.username = userdentista.email
        userdentista.set_password(form.cleaned_data.get("password"))
        if commit: 
            userdentista.save()
            Dentista.objects.create(usuario=userdentista,nome=(f'{userdentista.first_name} {userdentista.last_name}'))
            try:
                user_group = Group.objects.get(name="dentista")
            except Group.DoesNotExist:
                user_group = Group(name="dentista")
                user_group.save()
                user_group.permissions.set([Permission.objects.get(codename=c) for c in ["add_user", "change_user", "view_user", "view_clinica", "add_consulta", "change_consulta", "view_consulta","delete_consulta","add_restricao","change_restricao","delete_restricao","view_restricao", "view_exame","add_exame","change_exame","delete_exame", "view_pedido","add_pedido","change_pedido","delete_pedido", "view_dentista","change_dentista", "change_cliente", "view_cliente","view_procedimento","view_secretario","add_procedimento","change_procedimento","delete_procedimento",]])
            userdentista.groups.add(user_group)
        return userdentista
    
class DentistaForm(ModelForm):
    class Meta:
        model=Dentista
        fields=[
            'nome','cpf',
            'cro', 'especialidade',
            'telefone', 'salario',
            'data_contratacao','clinica',
            'rua','numero_residencial',
            'bairro','cep','cidade','estado',
        ]
        labels=[
            'Nome', 'CPF', 'CRO',
            'Especialidade',
            'Telefone', 'Salário',
            'Data Contratacao','Clínica',
            'Rua','Numero residencial',
            'Bairro','CEP','Cidade','Estado',
        ]

class UserSecretarioRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['first_name',
                  'last_name',
                  'email',
                  'password',
                  'confirm_password'
        ]

        labels = {'first_name':"Nome",
                'last_name':"Sobrenome",
                'email':"Email", 
                'password':"Senha",
                'confirm_password':"Confirmar senha"
        }

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password != confirm_password:
            raise forms.ValidationError("As senhas não coincidem.")
        
    def save(form,commit=True):
        usersecretario=super().save(commit=False) 
        usersecretario.tipo_usuario= 'secretary'
        usersecretario.username = usersecretario.email
        usersecretario.set_password(form.cleaned_data.get("password"))
        if commit: 
            usersecretario.save()
            Secretario.objects.create(usuario=usersecretario,nome=(f'{usersecretario.first_name} {usersecretario.last_name}'))
            try:
                user_group = Group.objects.get(name="secretario")
            except Group.DoesNotExist:
                user_group = Group(name="secretario")
                user_group.save()
                user_group.permissions.set([Permission.objects.get(codename=c) for c in ["add_user", "change_user", "view_user", "view_clinica","change_clinica", "add_consulta", "change_consulta", "view_consulta","delete_consulta","add_restricao","change_restricao","delete_restricao","view_restricao", "view_exame","add_exame","change_exame","delete_exame", "view_pedido","delete_pedido", "view_dentista","change_dentista", "change_cliente", "view_cliente","view_procedimento","view_secretario","change_secretario","add_procedimento","change_procedimento","delete_procedimento",]])
            usersecretario.groups.add(user_group)
        return usersecretario
    
class SecretarioForm(ModelForm):
    class Meta:
        model=Secretario
        fields=[
            'nome','cpf',
            'telefone', 'salario',
            'data_contratacao','clinica',
            'rua','numero_residencial',
            'bairro','cep','cidade','estado',
        ]
        labels=[
            'Nome', 'CPF', 
            'Telefone', 'Salário',
            'Data Contratacao','Clínica',
            'Rua','Numero residencial',
            'Bairro','CEP','Cidade','Estado',
        ]

class RestricaoDentistaForm(ModelForm):
    data = forms.DateField(widget=forms.SelectDateWidget)
    hora_inicio = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}))
    hora_fim = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}))
    dentista=forms.HiddenInput
    class Meta:
        model=Restricao
        fields=[
            'data',
            'hora_inicio', 'hora_fim',
        ]
        labels=[
            'Data', 
            'Ínício', 'Término',
        ]

class SelecionarDentistaForm(forms.Form):
    dentista = forms.ModelChoiceField(
        queryset=Dentista.objects.all(),
        label="Selecione o Dentista",
        empty_label="Escolha um dentista",
        widget=forms.Select(attrs={'class': 'form-control'})
    )

funcionarios/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.urls import reverse
from .models import Dentista,Secretario
from contas.models import User
from consultas.models import Restricao
from .forms import DentistaForm, UserDentistaRegistrationForm, SecretarioForm, UserSecretarioRegistrationForm, RestricaoDentistaForm
from datetime import date
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin

class CreateUserDentista(LoginRequiredMixin, PermissionRequiredMixin,generic.CreateView):
    permission_required = 'funcionarios.add_dentista'
    model=User
    template_name="funcionarios/createUserDentista.html"
    form_class=UserDentistaRegistrationForm
    def get_success_url(self):
        dentista = Dentista.objects.get(usuario=self.object.pk)
        return reverse('funcionarios:updateDentista',args=[dentista.pk])

class CreateDentista(LoginRequiredMixin, PermissionRequiredMixin,generic.CreateView):
    permission_required = 'funcionarios.add_dentista'
    model=Dentista
    template_name="funcionarios/createDentista.html"
    form_class=DentistaForm
    def get_success_url(self):
        return reverse('funcionarios:detailDentista', args=[self.object.pk])
       
class UpdateDentista(LoginRequiredMixin, PermissionRequiredMixin,generic.UpdateView):
    permission_required = 'funcionarios.change_dentista'
    model= Dentista
    template_name="funcionarios/updateDentista.html"
    form_class=DentistaForm
    def get_success_url(self):
        return reverse('funcionarios:detailDentista', args=[self.object.pk])

class DeleteDentista(LoginRequiredMixin, PermissionRequiredMixin,generic.DeleteView):
    permission_required = 'funcionarios.delete_dentista'
    model=Dentista
    template_name="funcionarios/deleteDentista.html"
    def get_success_url(self):
        return reverse('funcionarios:indexDentista')
    
class ListDentista(LoginRequiredMixin, PermissionRequiredMixin,generic.ListView):
    permission_required = 'funcionarios.view_dentista'
    model=Dentista
    template_name='funcionarios/indexDentista.html'

class DetailDentista(LoginRequiredMixin, PermissionRequiredMixin,generic.DetailView):
    permission_required = 'funcionarios.view_dentista'
    model=Dentista
    template_name='funcionarios/detailDentista.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        restricao_list = Restricao.objects.filter(dentista=self.object.pk,data__gte=date.today()).order_by('data','hora_inicio')
        context['restricao_list'] = restricao_list
        return context

def searchDentista(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        dentista_list = Dentista.objects.filter(nome__icontains=search_term)
        context = {"dentista_list": dentista_list}
    return render(request, 'funcionarios/searchDentista.html', context)

class CreateUserSecretario(LoginRequiredMixin, PermissionRequiredMixin,generic.CreateView):
    permission_required = 'funcionarios.add_secretario'
    model=User
    template_name="funcionarios/createUserSecretario.html"
    form_class=UserSecretarioRegistrationForm
    def get_success_url(self):
        secretario = Secretario.objects.get(usuario=self.object.pk)
        return reverse('funcionarios:updateSecretario',args=[secretario.pk])

class CreateSecretario(LoginRequiredMixin, PermissionRequiredMixin,generic.CreateView):
    permission_required = 'funcionarios.add_secretario'
    model=Secretario
    template_name="funcionarios/createSecretario.html"
    form_class=SecretarioForm
    def get_success_url(self):
        return reverse('funcionarios:detailSecretario', args=[self.object.pk])
       
class UpdateSecretario(LoginRequiredMixin, PermissionRequiredMixin,generic.UpdateView):
    permission_required = 'funcionarios.change_secretario'
    model= Secretario
    template_name="funcionarios/updateSecretario.html"
    form_class=SecretarioForm
    def get_success_url(self):
        return reverse('funcionarios:detailSecretario', args=[self.object.pk])

class DeleteSecretario(LoginRequiredMixin, PermissionRequiredMixin,generic.DeleteView):
    permission_required = 'funcionarios.delete_secretario'
    model=Secretario
    template_name="funcionarios/deleteSecretario.html"
    def get_success_url(self):
        return reverse('funcionarios:indexSecretario')
    
class ListSecretario(LoginRequiredMixin, PermissionRequiredMixin,generic.ListView):
    permission_required = 'funcionarios.view_secretario'
    model=Secretario
    template_name='funcionarios/indexSecretario.html'

class DetailSecretario(LoginRequiredMixin, PermissionRequiredMixin,generic.DetailView):
    permission_required = 'funcionarios.view_secretario'
    model=Secretario
    template_name='funcionarios/detailSecretario.html'

def searchSecretario(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        secretario_list = Dentista.objects.filter(nome__icontains=search_term)
        context = {"secretario_list": secretario_list}
    return render(request, 'funcionarios/searchSecretario.html', context)

class CreateRestricaoDentista(LoginRequiredMixin, PermissionRequiredMixin,generic.CreateView):
    permission_required = 'consultas.add_restricao'
    model=Restricao
    template_name="funcionarios/createRestricaoDentista.html"
    def get(self, request, pk):
        dentista=get_object_or_404(Dentista, id=pk)
        form = RestricaoDentistaForm()
        return render(request, 'funcionarios/createRestricaoDentista.html', {'form': form,'dentista':dentista})
    
    def post(self, request,pk):
        form = RestricaoDentistaForm(request.POST)
        if form.is_valid():
            restricao = form.save(commit=False)
            dentista=get_object_or_404(Dentista, id=pk)
            # Associa o dentista à restrição
            restricao.dentista= dentista
            # Salva a restrição
            restricao.save()
            return render(request, 'funcionarios/detailDentista.html', {'form': form,'dentista':dentista})
        return render(request, 'funcionarios/createRestricaoDentista.html', {'form': form})
    
    #def get_success_url(self):
        #return reverse('funcionarios:detailDentista',args=[self.object.dentista.pk])

class DeleteRestricao(LoginRequiredMixin, PermissionRequiredMixin,generic.DeleteView):
    permission_required = 'consultas.delete_restricao'
    model = Restricao
    def get_success_url(self):
        # Redireciona para a página de detalhes do dentista após a exclusão
        return reverse('funcionarios:detailDentista', kwargs={'pk': self.object.dentista.pk})

funcionarios/templates/funcionarios/createDentista.html
{% extends 'base.html' %} 
{% block content %}
<h2>Inserir Novo Dentista</h2>
<form class="formClass" method="POST" action="{% url 'funcionarios:createDentista' %}">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Criar</button>
</form>
{% endblock content %}

funcionarios/templates/funcionarios/createRestricaoDentista.html
{% extends 'base.html' %} 
{% block content %}
<h2>Inserir Restrição de horário para: {{ dentista.nome }}</h2>
<form class="formClass" method="POST" action="{% url 'funcionarios:horarioDentista' dentista.id %}">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Criar</button>
</form>
{% endblock content %}

funcionarios/templates/funcionarios/createSecretario.html
{% extends 'base.html' %} 
{% block content %}
<h2>Inserir Novo Secretario</h2>
<form class="formClass" method="POST" action="{% url 'funcionarios:createSecretario' %}">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Criar</button>
</form>
{% endblock content %}

funcionarios/templates/funcionarios/createUserDentista.html
{% extends 'base.html' %} 
{% block content %}
<h2>Inserir Novo Dentista</h2>
<form class="formClass" method="POST" action="{% url 'funcionarios:createUserDentista' %}">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Criar</button>
</form>
{% endblock content %}

funcionarios/templates/funcionarios/deleteDentista.html
{% extends 'base.html' %} 
{% block content %}
<form class="formClass" action="{% url 'funcionarios:deleteDentista' dentista.id %}" method="post">
    {% csrf_token %}
    <p>
      Você tem certeza que deseja apagar {{ dentista.nome }}?
    </p>
    <button type="submit">Apagar</button>
</form>
{% endblock content %}

funcionarios/templates/funcionarios/deleteSecretario.html
{% extends 'base.html' %} 
{% block content %}
<form class="formClass" action="{% url 'funcionarios:deleteSecretario' secretario.id %}" method="post">
    {% csrf_token %}
    <p>
      Você tem certeza que deseja apagar o post "{{ secretario.nome }} "?
    </p>
    <button type="submit">Apagar</button>
</form>
{% endblock content %}

funcionarios/templates/funcionarios/detailDentista.html
{% extends 'base.html' %}

{% block title %}
{{ dentista.nome }}
{% endblock title %}

{% block content %}
<div class="dentista-info">
    <ul class="dentista-dados">
        <li><strong>Dentista:</strong> {{ dentista.nome }}</li>
        <li><strong>Contratada em:</strong> {{ dentista.data_contratacao | date:"D, d M Y" }}</li>
        <li><a class="link" href="{% url 'funcionarios:horarioDentista' dentista.id %}">Horários</a></li>
        <li><a class="link" href="{% url 'funcionarios:updateDentista' dentista.id %}">Editar</a></li>
        <li><a class="link link-danger" href="{% url 'funcionarios:deleteDentista' dentista.id %}">Apagar</a></li>
    </ul>
</div>

{% if restricao_list %}
<section class="restricao-list">
    {% for restricao in restricao_list %}
    <article class="restricao-item">
        <p><strong>Data:</strong> {{ restricao.data }}</p>
        <p><strong>Horário:</strong> {{ restricao.hora_inicio }} - {{ restricao.hora_fim }}</p>
        <form method="post" action="{% url 'funcionarios:deleteRestricao' restricao.id %}" class="delete-form">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Excluir</button>
        </form>
    </article>
    {% endfor %}
</section>
{% else %}
<p class="no-restricoes">Não foi encontrado nenhuma restrição de horário.</p>
{% endif %}

{% endblock content %}

funcionarios/templates/funcionarios/detailSecretario.html
{% extends 'base.html' %} 

{% block title %} 
{{ secretario.nome }} 
{% endblock title %} 

{% block content %}
<ul>
    <li>Secretario: {{ secretario.nome }}</li>
    <li>Contratada em: {{ secretario.data_contratacao |date:"D, d M Y" }}</li>
    <li><a href="{% url 'funcionarios:updateSecretario' secretario.id %}">Editar </a></li>
    <li><a href="{% url 'funcionarios:deleteSecretario' secretario.id %}">Apagar </a></li>
  </ul>
{% endblock content %}

funcionarios/templates/funcionarios/indexDentista.html
{% extends 'base.html' %} 
{% block content %}
<h2>Todos os Dentistas</h2>

<section>
  <p>
    Muitos resultados? <a href="{% url 'funcionarios:searchDentista' %}">Buscar Dentista</a>
  </p>
  <p>
    <a href="{% url 'funcionarios:createUserDentista' %}">Adicionar Novo Dentista</a>
  </p>
</section>
<hr>
{% if dentista_list %}
<section>
  {% for dentista in dentista_list %}
  <article>
    <a href="{% url 'funcionarios:detailDentista' dentista.id %}">
      <p>{{ dentista.nome }}</p>
    </a>
  </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum dentista.</p>
{% endif %} 
{% endblock content %}

funcionarios/templates/funcionarios/indexSecretario.html
{% extends 'base.html' %} 
{% block content %}
<h2>Todos os Secretarios</h2>

<section>
  <p>
    Muitos resultados? <a href="{% url 'funcionarios:searchSecretario' %}">Buscar Secretário</a>
  </p>
  <p>
    <a href="{% url 'funcionarios:createUserSecretario' %}">Adicionar Novo Secretário</a>
  </p>
</section>
<hr>
{% if secretario_list %}
<section>
  {% for secretario in secretario_list %}
  <article>
    <a href="{% url 'funcionarios:detailSecretario' secretario.id %}">
      <p>{{ secretario.nome }}</p>
    </a>
  </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum secretário.</p>
{% endif %} 
{% endblock content %}

funcionarios/templates/funcionarios/searchDentista.html
{% extends 'base.html' %} 
{% block content %}

<h2>Busca de Dentista por Nome</h2>
<form class="formClass" action="{% url 'funcionarios:searchDentista' %}">
    <p>
        <label for="id_query">Nome:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>

<h2>Dentistas Filtrados</h2>
{% if dentista_list %}
<section>
  {% for dentista in dentista_list %}
  <article>
    <a href="{% url 'funcionarios:detailDentista' dentista.id %}">
      <p>{{ dentista.nome }} ({{ dentista.especialidade}})</p>
    </a>
  </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum Dentista.</p>
{% endif %} 
{% endblock content %}

funcionarios/templates/funcionarios/searchSecretario.html
{% extends 'base.html' %} 
{% block content %}

<h2>Busca de Secretario por Nome</h2>
<form class="formClass" action="{% url 'funcionarios:searchSecretario' %}">
    <p>
        <label for="id_query">Nome:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>

<h2>Secretarios Filtrados</h2>
{% if secretario_list %}
<section>
  {% for secretario in secretario_list %}
  <article>
    <a href="{% url 'funcionarios:detailSecretario' secretario.id %}">
      <p>{{ secretario.nome }} ({{ secretario.clinica}})</p>
    </a>
  </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum Secretario.</p>
{% endif %} 
{% endblock content %}

funcionarios/templates/funcionarios/updateDentista.html
{% extends 'base.html' %} 
{% block content %}
<h2>Atualizar Dentista</h2>
<form class="formClass" method="POST" action="{% url 'funcionarios:updateDentista' dentista.id %}">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Atualizar</button>
</form>
{% endblock content %}

funcionarios/templates/funcionarios/updateSecretario.html
{% extends 'base.html' %} 
{% block content %}
<h2>Atualizar Secretario</h2>
<form class="formClass" method="POST" action="{% url 'funcionarios:updateSecretario' secretario.id %}">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Atualizar</button>
</form>
{% endblock content %}